[program:manake-scheduler]
directory=/var/www/manake-rental
command=/usr/bin/php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/manake-scheduler.log
environment=APP_ENV="production",APP_DEBUG="false"
