[program:manake-queue-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/manake-rental
command=/usr/bin/php artisan queue:work --queue=default --sleep=1 --tries=3 --timeout=120 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/manake-queue-worker.log
stopwaitsecs=3600
environment=APP_ENV="production",APP_DEBUG="false"
